version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: webdb
      MYSQL_USER: jay
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    image: jay11233/ec2-user-web:latest
    build: ./web
    deploy:
      replicas: 6
    environment:
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '--nginx.scrape-uri=http://nginx:80/nginx_status'
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    user: "${UID:-1000}:${GID:-1000}"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
volumes:
  mysql_data: